name: gallery_cleaner_ai
description: AI-powered gallery cleaner app that helps users organize their photos by detecting blurry, small, and non-person images.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Gallery Access
  photo_manager: ^3.0.0

  # Permissions
  permission_handler: ^11.0.1

  # Image Processing
  image: ^4.1.3

  # AI/ML
  tflite_flutter: ^0.10.4

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0

  # Animations
  lottie: ^2.7.0

  # Utils
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
